# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1636cf7a93099710fbaf876c2f2a4a4d"
name = "Variant Badges"
application_url = "https://variant-badges-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c559582d.myshopify.com"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app_uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers_data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers_redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop_redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products"

[auth]
redirect_urls = [
  "https://variant-badges-app-production.up.railway.app/auth/callback"
]

[pos]
embedded = false