[[extensions]]
type = "admin_link"
name = "Manage Badges"
handle = "manage-badges-details"

[[extensions.targeting]]
target = "admin.product-details.action.link"
url = "/api/admin/product-link"

[[extensions]]
type = "admin_link"
name = "Manage Badges"
handle = "manage-badges-index"

[[extensions.targeting]]
target = "admin.product-index.action.link"
url = "/api/admin/product-link"
